### ISSUE TITLE
Adding timezone selection during filtering data

### ISSUE THREAD

**Issue by narsi345** [implydata/pivot#161]
Hi , 

Can we get timezone selection dropdown option added to the UI during filtering data. 
Our customers (editors) are using pivot as defacto UI on top of druid for content programming on our web portals.

Is the feature request is already on the pipeline  ?

**Comment by asherbitter** [comment]
Hi,

Timezone selection UI is on the roadmap, though there is no specific timeline for it at the moment.

**Comment by vogievetsky** [comment]
Latest Pivot release (0.8.22) comes with a timezone selection UI and comprehensive timezone support.

**Comment by asherbitter** [comment]
You can find it here:
<img width="289" alt="screen shot 2016-05-05 at 12 20 20 am" src="https://cloud.githubusercontent.com/assets/957611/15029654/36d534dc-1257-11e6-977d-73f358e84200.png">

**Comment by narsi345** [comment]
Thanks very much for adding this feature very quick.

On some of our pivot nodes , i m seeing this node missing "date" module on
upgrading pivot to the latest version . Anything i am missing out ?

Did a npm install  -g    date but still seeing the error

date@1.0.2 /usr/lib/node_modules/date


module.js:327

    throw err;

    ^


Error: Cannot find module '../../../client/utils/date/date'

    at Function.Module._resolveFilename (module.js:325:15)

    at Function.Module._load (module.js:276:25)

    at Module.require (module.js:353:17)

    at require (internal/module.js:12:17)

    at Object.<anonymous>
(/usr/lib/node_modules/imply-pivot/build/common/models/data-source/data-source.js:8:14)

    at Module._compile (module.js:409:26)

    at Object.Module._extensions..js (module.js:416:10)

    at Module.load (module.js:343:32)

    at Function.Module._load (module.js:300:12)

    at Module.require (module.js:353:17)

    at require (internal/module.js:12:17)



On Wed, May 4, 2016 at 2:07 PM, Vadim Ogievetsky <notifications@github.com>
wrote:

> Latest Pivot release (0.8.22) comes with a timezone selection UI and
> comprehensive timezone support.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/implydata/pivot/issues/161#issuecomment-217003141>
>



-- 
narsi

**Comment by vogievetsky** [comment]
Sorry for that missing date module error. It was a problem with the npm build. Please update your Pivot to 0.8.23

**Comment by narsi345** [comment]
It worked after updating to 0.8.23.
Thanks again for accepting feature requests and releasing them in time.



On Wed, May 4, 2016 at 2:53 PM, Vadim Ogievetsky <notifications@github.com>
wrote:

> Sorry for that missing date module error. It was a problem with the npm
> build. Please update your Pivot to 0.8.23
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/implydata/pivot/issues/161#issuecomment-217015110>
>



-- 
narsi
